### ISSUE TITLE
java.lang.ClassNotFoundException: com.parachute.common.Parachute (1.8)

### ISSUE THREAD

**Issue by DanTheColoradan** [m1k3s/parachute#3]
I put this on the Curses project page, but didn't realize you have a github repo for it - feel free to delete that comment if you haven't already.

I tried both the 1.8 recommended and latest Forge releases. Without the mod, Minecraft loads fine. With the old parachute mod version (1.7...) it loads, but with the 1.8 version, it crashes with this error at startup:

```{.java}
---- Minecraft Crash Report ----

*** ATTENTION: detected classes with unsupported format ***
*** DO NOT SUBMIT THIS CRASH REPORT TO FORGE ***

Contact authors of the following mods: 
  parachutemod

// Daisy, daisy...

Time: 3/5/15 11:29 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.ClassNotFoundException: com.parachute.common.Parachute
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:162)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:503)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:412)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:325)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.parachute.common.Parachute
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at net.minecraftforge.fml.common.ModClassLoader.loadClass(ModClassLoader.java:60)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:249)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:425)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:493)
	... 10 more
Caused by: java.lang.UnsupportedClassVersionError: com/parachute/common/Parachute : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 38 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Mac OS X (x86_64) version 10.10.2
	Java Version: 1.6.0_65, Apple Inc.
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
	Memory: 51134064 bytes (48 MB) / 266809344 bytes (254 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.10 FML v8.0.42.1336 Minecraft Forge 11.14.1.1336 4 mods loaded, 4 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed
	FML{8.0.42.1336} [Forge Mod Loader] (forge-1.8-11.14.1.1336.jar) Unloaded->Constructed
	Forge{11.14.1.1336} [Minecraft Forge] (forge-1.8-11.14.1.1336.jar) Unloaded->Constructed
	parachutemod{3.1.1} [Parachute Mod] (parachutemod-1.8.0-3.1.1-13.jar) Unloaded->Errored
	Loaded coremods (and transformers): 
```

**Comment by m1k3s** [comment]
I can not reproduce that error. I tested on both client and server. And again today, the mod works. I don't know what the "Unsupported major.minor version 51.0" part is all about. The supported MC version is 1.8.0 in the code. I am using forge-1.8-11.14.1.1336.
I'll try to do some research to figure out what that error is.

**Comment by DanTheColoradan** [comment]
Yah. My brother is using Windows (I'm on Mac OS X) and his starts up just fine. It's very odd. I'm not sure if there is some sort of preference file I could delete, or what. I removed Parachute Mod and installed Sophisticated Wolves and that works so I don't *think* it is Forge... I'll let you know if I see anything else.

**Comment by m1k3s** [comment]
You could try removing the parachute.cfg in the config folder. That shouldn't have anything to do with this, but ya never know.

**Comment by DanTheColoradan** [comment]
It would seem it doesn't get to that point since there isn't that file in the folder.

![screen shot 2015-03-05 at 12 29 18 pm](https://cloud.githubusercontent.com/assets/3826143/6512799/ca2e6e98-c333-11e4-9e62-0a6c46bab706.png)

I added a blank parachute.cfg and still the same error.

**Comment by m1k3s** [comment]
Okay, I realize now that you are using java 6. 
from the crash log:
Java Version: 1.6.0_65, Apple Inc.

All my mods have a java 7 minimum requirement. So I have rebuilt the parachute mod allowing java 6 as the minimum version. I posted the new version on CurseForge. If you wouldn't mind trying it (build 15) that may solve this issue.

**Comment by DanTheColoradan** [comment]
Huh. I might have to go to 6 soon then.

Does it take a bit to propagate to CurseForge?

![screen shot 2015-03-05 at 2 13 07 pm](https://cloud.githubusercontent.com/assets/3826143/6514721/ca2acfd2-c341-11e4-9da9-ad7c304e6e01.png)

**Comment by m1k3s** [comment]
The new upload is still under review. They should have it up shortly. If you can upgrade to java 7 you probably should. But I think Apple controls that, so good luck.

**Comment by DanTheColoradan** [comment]
Awesome. It works now. Thanks :)

**Comment by m1k3s** [comment]
I'll quit building for 1.7 minimum. I can see I didn't think it through. Thanks for the report.

**Comment by DanTheColoradan** [comment]
Honestly, I also installed Java 1.8 and I'm going to use that, but I'm pretty computer savvy. I did test it on 1.6 though.
