### ISSUE TITLE
MC 1.9, Forge 12.16.0.1863, Private Server Crash (Client side init failure)

### ISSUE THREAD

**Issue by JonnyBrando** [m1k3s/parachute#9]
Hello, I've been using your parachute mod on 1.7.10, 1.8, and 1.8.9.

It is working client-side on 1.9, but is failing to launch on my private server because it is loading client-side components on the server-side.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLPlugin (InventoryTweaks-1.61-dev-45.jar)
  MMFMLCorePlugin (MultiMine-1.9.jar)
  BetterFoliageLoader (BetterFoliage-MC1.9-2.0.8.jar)
  SCFMLCorePlugin (StalkerCreepers-1.9.jar)
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 4/10/16 8:59 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:179)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:559)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:93)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:320)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:119)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
	at com.parachute.common.ConfigHandler.<clinit>(ConfigHandler.java:50)
	at com.parachute.common.Parachute.preInit(Parachute.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:228)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:206)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:556)
	... 5 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.resources.I18n
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 33 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 35 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.9
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_66, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 204252432 bytes (194 MB) / 479260672 bytes (457 MB) up to 8563130368 bytes (8166 MB)
	JVM Flags: 7 total; -Xms350m -Xmx8G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -XX:+AggressiveOpts -Xmn256M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.23 Powered by Forge 12.16.0.1863 24 mods loaded, 24 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9-12.16.0.1863-1.9-universal.jar) 
	UCH	Forge{12.16.0.1863} [Minecraft Forge] (forge-1.9-12.16.0.1863-1.9-universal.jar) 
	UCH	Baubles{1.2.0.0} [Baubles] (Baubles-1.9-1.2.0.0.jar) 
	UCH	BetterAchievements{0.2.2} [Better Achievements] (BetterAchievements-1.9-0.2.2.jar) 
	UCH	BetterFoliage{2.0.8} [Better Foliage] (BetterFoliage-MC1.9-2.0.8.jar) 
	UCH	BiomesOPlenty{4.0.2.2008} [Biomes O' Plenty] (BiomesOPlenty-1.9-4.0.2.2008-universal.jar) 
	UCH	Chameleon{1.9-2.1.3} [Chameleon] (Chameleon-1.9-2.1.3.jar) 
	UCH	chisel{@VERSION@} [Chisel] (Chisel-MC1.9-0.0.4.13.jar) 
	UCH	graves{1.9-b8-universal} [Graves Mod] (graves-1.9-b8-universal.jar) 
	UCH	LunatriusCore{1.1.2.33} [LunatriusCore] (LunatriusCore-1.9-1.1.2.33-universal.jar) 
	UCH	InGameInfoXML{2.8.1.git} [InGame Info XML] (InGameInfoXML-1.9-2.8.1.git-forge12.16.0.1863-universal.jar) 
	UCH	inventorysorter{0.7.10+29} [Simple Inventory sorting] (inventorysorter-1.9-0.7.10+29.jar) 
	UCH	inventorytweaks{1.61-dev-45-29e0ed5} [Inventory Tweaks] (InventoryTweaks-1.61-dev-45.jar) 
	UCH	JEI{3.2.10.185} [Just Enough Items] (jei_1.9-3.2.10.185.jar) 
	UCH	journeymap{1.9-5.1.6b2} [JourneyMap] (journeymap-1.9-5.1.6b2-unlimited.jar) 
	UCH	mantle{1.9-0.9.4.DEV.91be353} [Mantle] (Mantle-1.9-0.9.4.DEV-forge12.16.0.1863-universal.jar) 
	UCH	AS_MultiMine{1.5.2} [Multi Mine] (MultiMine-1.9.jar) 
	UCE	parachutemod{1.4.1} [Parachute Mod] (parachutemod-ng-1.9-1.4.1-391.jar) 
	UCH	progressiveautomation{1.6.38} [Progressive Automation] (ProgressiveAutomation-1.9-1.6.38.jar) 
	UCH	AS_Ruins{15.8} [Ruins Spawning System] (Ruins-1.9.jar) 
	UCH	StorageDrawers{1.9-3.1.4} [Storage Drawers] (StorageDrawers-1.9-3.1.4.jar) 
	UCH	tconstruct{1.9-2.2.2.DEV.8ac8d11} [Tinkers' Construct] (TConstruct-1.9-2.2.2.DEV-forge12.16.0.1863-universal.jar) 
	UCH	AS_UpdateCheck{1.1.7} [AtomicStryker Update Check Mod] (UpdateCheckerMod-1.9.jar) 
	Loaded coremods (and transformers): 
FMLPlugin (InventoryTweaks-1.61-dev-45.jar)
  invtweaks.forge.asm.ContainerTransformer
MMFMLCorePlugin (MultiMine-1.9.jar)
  atomicstryker.multimine.common.fmlmagic.MMTransformer
BetterFoliageLoader (BetterFoliage-MC1.9-2.0.8.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
SCFMLCorePlugin (StalkerCreepers-1.9.jar)
  atomicstryker.stalkercreepers.common.SCTransformer
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)

	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by m1k3s** [comment]
I see the issue. I'll work on getting that resolved. 
**Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
at com.parachute.common.ConfigHandler.(ConfigHandler.java:50)**

**Comment by m1k3s** [comment]
I have fixed the server/client crash issue. Client side methods were being called on the server. Both language and sound methods. Now using the appropriate sided methods.

**Comment by JonnyBrando** [comment]
Thank you, Michael!

Love your mod, keep up the great work!


Jonathan

Date: Mon, 11 Apr 2016 08:38:28 -0700

**Comment by m1k3s** [comment]
Thanks! You'd think I would have tested on the server after making that many changes to update to 1.9.
